# NOTE: Generated By HttpRunner v3.1.4
# FROM: har\get_ip.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetIp(HttpRunner):

    config = Config("testcase description").base_url("${ENV(base_url)}").verify(False)

    teststeps = [
        Step(
            RunRequest("/cgi-bin/gettoken")
            .get("/cgi-bin/gettoken")
            .with_params(
                **{
                    "corpid": "ww93348658d7c66ef4",
                    "corpsecret": "T0TFrXmGYel167lnkzEydsjl6bcDDeXVmkUnEYugKIw",
                }
            )
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                    "Host": "qyapi.weixin.qq.com",
                    "Postman-Token": "3766c14a-7cfb-4d37-9448-b0d2274b713d",
                    "User-Agent": "PostmanRuntime/7.26.8",
                }
            )
            .extract()
            .with_jmespath("body.access_token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=UTF-8")
        ),
        Step(
            RunRequest("/cgi-bin/getcallbackip")
            .get("/cgi-bin/getcallbackip")
            .with_params(**{"access_token": "$token"})
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                    "Host": "qyapi.weixin.qq.com",
                    "Postman-Token": "127ef95d-c4a3-4799-865e-544fe7271b75",
                    "User-Agent": "PostmanRuntime/7.26.8",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=UTF-8")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetIp().test_start()
